const teachers=[
{id:"farahani",name:"فراهانی",subject:"شیمی",course:"جامع ۱۴۰۶",icon:"🧪",sessions:[]},
{id:"farahmand-nia",name:"فرهمند نیا",subject:"زیست‌شناسی",course:"جامع ۱۴۰۶",icon:"🧬",sessions:[]},
{id:"karami",name:"کرمی",subject:"ریاضی",course:"جامع ۱۴۰۶",icon:"📐",sessions:[]}
];
const homePage=document.getElementById("homePage"),teacherPage=document.getElementById("teacherPage"),teachersContainer=document.getElementById("teachersContainer"),sessionsContainer=document.getElementById("sessionsContainer"),teacherHeader=document.getElementById("teacherHeader");
function renderTeachers(){teachersContainer.innerHTML="";teachers.forEach(t=>{const c=document.createElement("div");c.className="teacher-card";c.onclick=()=>openTeacher(t.id);c.innerHTML=`<div class="teacher-avatar">${t.icon}</div><div class="teacher-name">${t.name}</div><div class="teacher-subject">${t.subject}</div><div class="teacher-course">${t.course}</div><div class="teacher-button">ورود به کلاس ←</div>`;teachersContainer.appendChild(c)})}
function openTeacher(id){const t=teachers.find(x=>x.id===id);if(!t)return;teacherHeader.innerHTML=`<div class="teacher-header"><h1>${t.name}</h1><p>${t.subject}</p><div class="course">${t.course}</div></div>`;sessionsContainer.innerHTML="";if(!t.sessions.length){sessionsContainer.innerHTML='<div class="session"><div class="session-top"><div class="session-title">جلسات این دوره به‌زودی اضافه می‌شوند.</div></div></div>'}else t.sessions.forEach(s=>{const e=document.createElement("div");e.className="session";e.innerHTML=`<div class="session-top"><div class="session-info"><div class="session-number">${String(s.number).padStart(2,"0")}</div><div class="session-title">${s.title}</div></div></div><div class="session-links"><a href="${s.classLink}" class="session-link" target="_blank" rel="noopener">🎬 مشاهده کلاس</a><a href="${s.bookletLink}" class="session-link" target="_blank" rel="noopener">📄 جزوه</a><a href="${s.resourcesLink}" class="session-link" target="_blank" rel="noopener">📚 منابع</a></div>`;sessionsContainer.appendChild(e)});homePage.classList.remove("active");teacherPage.classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}
function showHome(){teacherPage.classList.remove("active");homePage.classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}renderTeachers();
